// Auth area
export const LOGIN_PHONE_SUCCESS = "LOGIN_PHONE_SUCCESS";
export const LOGIN_PHONE_ERROR = "LOGIN_PHONE_ERROR";
export const SIGNUP_SUCCES = "SIGNUP_SUCCES";
export const SIGNUP_FAIL = "SIGNUP_FAIL ";
export const CONFIRM_OTP_SUCCESS = "CONFIRM_OTP_SUCCESS";
export const CONFIRM_OTP_FAIL = "CONFIRM_OTP_FAIL";

export const GET_ALL_PROJECT = "GET_ALL_PROJECT";
export const TEST_PHONE = "TEST_PHONE";
//  default message for login, confirm Otp
export const LOGIN_PHONE_SUCCESS_MESSAGE = "LOGIN_PHONE_SUCCESS_MESSAGE";
export const CONFIRM_OTP_SUCCESS_MESSAGE = "CONFIRM_OTP_SUCCESS_MESSAGE";
