const banks = [
  { key: "39", text: "Vietcombank", value: "39" },
  { key: "40", text: "Vietinbank", value: "40" },
  { key: "41", text: "BIDV", value: "41" },
  { key: "42", text: "Agribank", value: "42" },
  { key: "12", text: "VPBank", value: "12" },
  { key: "6", text: "Sacombank", value: "6" },
  { key: "10", text: "ACB", value: "10" },
  { key: "50", text: "HSBC", value: "50" },
  { key: "7", text: "DongA Bank", value: "7" },
  { key: "63", text: "TPBank", value: "63" },
  { key: "8", text: "EximBank", value: "8" },
  { key: "16", text: "VIB", value: "16" },
  { key: "24", text: "SHB", value: "24" },
  { key: "21", text: "OCB", value: "21" },
  { key: "52", text: "Shinhan Bank", value: "52" },
  { key: "29", text: "Vietbank", value: "29" },
  { key: "31", text: "PG Bank", value: "31" },
  { key: "22", text: "SCB", value: "22" },
  { key: "5", text: "Maritime Bank", value: "5" },
  { key: "26", text: "ABBank", value: "26" },
  { key: "13", text: "Techcombank", value: "13" },
  { key: "14", text: "MBBank", value: "14" },
  { key: "35", text: "LienVietPostBank", value: "35" },
  { key: "17", text: "SeABank", value: "17" },
  { key: "51", text: "Standard Chartered", value: "51" },
  { key: "20", text: "PVcomBank", value: "20" },
  { key: "92", text: "UOB", value: "92" },
  { key: "36", text: "First Bank", value: "36" },
  { key: "23", text: "Woori Bank", value: "23" },
  { key: "9", text: "Nam A Bank", value: "9" },
  { key: "11", text: "Saigonbank", value: "11" },
  { key: "15", text: "Bac A Bank", value: "15" },
  { key: "18", text: "HDBank", value: "18" },
  { key: "60", text: "Viet Capital Bank", value: "60" },
  { key: "32", text: "VietABank", value: "32" },
  { key: "25", text: "GPBank", value: "25" },
  { key: "27", text: "NCB", value: "27" },
  { key: "28", text: "KienLong Bank", value: "28" },
  { key: "30", text: "OceanBank", value: "30" },
  { key: "33", text: "CBBank", value: "33" },
  { key: "38", text: "BAOVIET Bank", value: "38" },
  { key: "44", text: "VBSP", value: "44" },
  { key: "45", text: "VDB", value: "45" },
  { key: "46", text: "Public Bank Việt Nam", value: "46" },
  { key: "47", text: "Indovina Bank", value: "47" },
  { key: "49", text: "VRB", value: "49" },
  { key: "54", text: "HongLeong Bank", value: "54" }
];

export default banks;
