const provinces = [
  { key: "89", value: "89", text: "An Giang" },
  { key: "77", value: "77", text: "Bà Rịa - Vũng Tàu" },
  { key: "74", value: "74", text: "Bình Dương" },
  { key: "70", value: "70", text: "Bình Phước" },
  { key: "60", value: "60", text: "Bình Thuận" },
  { key: "52", value: "52", text: "Bình Định" },
  { key: "95", value: "95", text: "Bạc Liêu" },
  { key: "24", value: "24", text: "Bắc Giang" },
  { key: "06", value: "06", text: "Bắc Kạn" },
  { key: "27", value: "27", text: "Bắc Ninh" },
  { key: "83", value: "83", text: "Bến Tre" },
  { key: "04", value: "04", text: "Cao Bằng" },
  { key: "96", value: "96", text: "Cà Mau" },
  { key: "92", value: "92", text: "Cần Thơ" },
  { key: "11", value: "11", text: "Điện Biên" },
  { key: "48", value: "48", text: "Đà Nẵng" },
  { key: "66", value: "66", text: "Đắk Lắk" },
  { key: "67", value: "67", text: "Đắk Nông" },
  { key: "75", value: "75", text: "Đồng Nai" },
  { key: "87", value: "87", text: "Đồng Tháp" },
  { key: "64", value: "64", text: "Gia Lai" },
  { key: "17", value: "17", text: "Hoà Bình" },
  { key: "02", value: "02", text: "Hà Giang" },
  { key: "35", value: "35", text: "Hà Nam" },
  { key: "01", value: "01", text: "Hà Nội" },
  { key: "42", value: "42", text: "Hà Tĩnh" },
  { key: "33", value: "33", text: "Hưng Yên" },
  { key: "30", value: "30", text: "Hải Dương" },
  { key: "31", value: "31", text: "Hải Phòng" },
  { key: "93", value: "93", text: "Hậu Giang" },
  { key: "79", value: "79", text: "Hồ Chí Minh" },
  { key: "56", value: "56", text: "Khánh Hòa" },
  { key: "91", value: "91", text: "Kiên Giang" },
  { key: "62", value: "62", text: "Kon Tum" },
  { key: "12", value: "12", text: "Lai Châu" },
  { key: "80", value: "80", text: "Long An" },
  { key: "10", value: "10", text: "Lào Cai" },
  { key: "68", value: "68", text: "Lâm Đồng" },
  { key: "20", value: "20", text: "Lạng Sơn" },
  { key: "36", value: "36", text: "Nam Định" },
  { key: "40", value: "40", text: "Nghệ An" },
  { key: "37", value: "37", text: "Ninh Bình" },
  { key: "58", value: "58", text: "Ninh Thuận" },
  { key: "25", value: "25", text: "Phú Thọ" },
  { key: "54", value: "54", text: "Phú Yên" },
  { key: "44", value: "44", text: "Quảng Bình" },
  { key: "49", value: "49", text: "Quảng Nam" },
  { key: "51", value: "51", text: "Quảng Ngãi" },
  { key: "22", value: "22", text: "Quảng Ninh" },
  { key: "45", value: "45", text: "Quảng Trị" },
  { key: "94", value: "94", text: "Sóc Trăng" },
  { key: "14", value: "14", text: "Sơn La" },
  { key: "38", value: "38", text: "Thanh Hóa" },
  { key: "34", value: "34", text: "Thái Bình" },
  { key: "19", value: "19", text: "Thái Nguyên" },
  { key: "46", value: "46", text: "Thừa Thiên Huế" },
  { key: "82", value: "82", text: "Tiền Giang" },
  { key: "84", value: "84", text: "Trà Vinh" },
  { key: "08", value: "08", text: "Tuyên Quang" },
  { key: "72", value: "72", text: "Tây Ninh" },
  { key: "86", value: "86", text: "Vĩnh Long" },
  { key: "26", value: "26", text: "Vĩnh Phúc" },
  { key: "15", value: "15", text: "Yên Bái" }
];

export default provinces;
